liquibase:
  url: "jdbc:postgresql://172.18.208.3:5432/production"
  user: "postgres"
  password: "postgres"

virtualService:
  hosts:
    - "toway.xyz"   # todo add real host ex. 'licensepro.com'

canaryTrafficPercentage: 0

app-service-a:
  environment: PRODUCTION
  stable:
    replicas: 1
    image:
      repository: zonex5cpb
      name: service-a
      tag: "1.9"
  canary:
    enabled: false
  destinationRule:
    subsets:
      - name: stable
        labels:
          version: stable
  database:
    url: "jdbc:postgresql://172.18.208.3:5432/production"
    user: "postgres"
    password: "postgres"