liquibase:
  url: "jdbc:postgresql://172.18.208.3:5432/stage"
  user: "postgres"
  password: "postgres"

virtualService:
  hosts:
    - "*"   # todo add real host ex. 'stage.licensepro.com'
  gateways:
    - "stage-gateway"

canaryTrafficPercentage: 0

app-service-a:
  stable:
    replicas: 1
    image:
      repository: zonex5cpb
      name: service-a
      tag: "v.0.1"
  canary:
    enabled: false
  virtualService:
    hosts:
      - "*"   # todo add real host ex. 'stage.licensepro.com'
    gateways:
      - "stage-gateway"
  destinationRule:
    subsets:
      - name: stable
        labels:
          version: stable
  database:
    url: "jdbc:postgresql://172.18.208.3:5432/stage"
    user: "postgres"
    password: "postgres"
