liquibase:
  url: "jdbc:postgresql://172.18.208.3:5432/stage"
  user: "postgres"
  password: "postgres"

ui:
  version: "stage.1"

virtualService:
  hosts:
    - "stage.toway.xyz"   # todo add real host ex. 'stage.licensepro.com'

canaryTrafficPercentage: 0

app-service-a:
  environment: STAGE
  stable:
    replicas: 1
    image:
      repository: zonex5cpb
      name: service-a
      tag: "0.1"
  canary:
    enabled: false
  destinationRule:
    subsets:
      - name: stable
        labels:
          version: stable
  database:
    url: "jdbc:postgresql://172.18.208.3:5432/stage"
    user: "postgres"
    password: "postgres"
