liquibase:
  url: "jdbc:postgresql://172.18.208.3:5432/production"
  user: "postgres"
  password: "postgres"

virtualService:
  hosts:
    - "*"   # todo add real host ex. 'licensepro.com'
  gateways:
    - "prod-gateway"

canaryTrafficPercentage: 0

app-service-a:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: service-a
      tag: latest
  canary:
    enabled: false
  virtualService:
    hosts:
      - "*"   # todo add real host ex. 'licensepro.com'
    gateways:
      - "prod-gateway"
  destinationRule:
    subsets:
      - name: stable
        labels:
          version: stable
  database:
    url: "jdbc:postgresql://172.18.208.3:5432/service_a"
    user: "postgres"
    password: "postgres"