virtualService:
  hosts:
    - "*"   # todo add real host ex. 'stage.licensepro.com'
  gateways:
    - "stage-gateway"

canaryTrafficPercentage: 0

app-service-a:
  stable:
    replicas: 3
    image:
      repository: localhost:5000
      name: service-a
      tag: "1.1"
  canary:
    enabled: false
  virtualService:
    hosts:
      - "*"   # todo add real host ex. 'stage.licensepro.com'
    gateways:
      - "stage-gateway"
  destinationRule:
    subsets:
      - name: stable
        labels:
          version: stable