apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{.Chart.Name}}