apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-migration
  namespace: migrations
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          #command: [ "/bin/sh", "-c", "git clone https://github.com/zonex5/service-a /workspace" ]
          #command: [ "/bin/sh", "-c", "apk add --no-cache openssh && \
          #            mkdir -p /tmp/.ssh && \
          #            cp /root/.ssh/id_rsa /tmp/.ssh/id_rsa && chmod 600 /tmp/.ssh/id_rsa && \
          #            ssh-keyscan -H github.com > /tmp/.ssh/known_hosts && \
          #            GIT_SSH_COMMAND='ssh -o UserKnownHostsFile=/tmp/.ssh/known_hosts -i /tmp/.ssh/id_rsa' git clone git@github.com:zonex5/service-a.git /workspace" ]
          command: [ "/bin/sh", "-c", "mkdir -p /tmp/.ssh && \
                      cp /root/.ssh/id_rsa /tmp/.ssh/id_rsa && chmod 600 /tmp/.ssh/id_rsa && \
                      ssh-keyscan -H github.com > /tmp/.ssh/known_hosts && \
                      GIT_SSH_COMMAND='ssh -o UserKnownHostsFile=/tmp/.ssh/known_hosts -i /tmp/.ssh/id_rsa' \
                      git clone git@github.com:zonex5/service-a.git /workspace" ]
          volumeMounts:
            - name: changelog-volume
              mountPath: /workspace
            - name: ssh-key-volume
              mountPath: /root/.ssh
      containers:
        - name: liquibase
          image: liquibase/liquibase:latest
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: "{{.Values.liquibase.url}}"
            - name: LIQUIBASE_COMMAND_USERNAME
              value: "{{.Values.liquibase.user}}"
            - name: LIQUIBASE_COMMAND_PASSWORD
              value: "{{.Values.liquibase.password}}"
          args:
            - "--changeLogFile=changelog.xml"
            - "update"
          workingDir: /repo/migrations
          volumeMounts:
            - name: changelog-volume
              mountPath: /repo
      volumes:
        - name: changelog-volume
          emptyDir: { }
        - name: ssh-key-volume
          secret:
            secretName: argocd-access-key-secret