apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Namespace }}-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  {{- toYaml .Values.virtualService.hosts | nindent 2 }}
  gateways:
  {{- toYaml (list (printf "%s-gateway" .Release.Namespace)) | nindent 2 }}
  http:
    - match:
        - uri:
            prefix: /a
      route:
        - destination:
            host: app-service-a-service.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080