apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Namespace }}-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  {{- toYaml .Values.virtualService.hosts | nindent 2 }}
  gateways:
    - istio-system/main-gateway
  http:
    - match:
        - uri:
            prefix: /values
        - uri:
            prefix: /test
        - uri:
            prefix: /env
      route:
        - destination:
            host: app-service-a-service.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
      # default request
      - route:
          - destination:
              host: ui-service