apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: liquibase-migration
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zonex5/argocd-service-a.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: liquibase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
